services:
  edit-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: edit
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "-c include_dir=/opt/postgresql/conf.d/"
    ports:
      - "54321:5432"
    volumes:
      - type: bind
        source: ./docker-compose/initdb.sh
        target: /docker-entrypoint-initdb.d/initdb.sh
      - type: bind
        source: ./docker-compose/initdb.sql
        target: /docker-entrypoint-initdb.d/initdb.sql
      - type: bind
        source: ./docker-compose/postgresql-custom.conf
        target: /opt/postgresql/conf.d/postgresql-custom.conf
      - type: volume
        source: pgdata_edit
        target: /var/lib/postgresql/data
  pub-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: pub
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "-c include_dir=/opt/postgresql/conf.d/"
    ports:
      - "54322:5432"
    volumes:
      - type: bind
        source: ./docker-compose/initdb.sh
        target: /docker-entrypoint-initdb.d/initdb.sh
      - type: bind
        source: ./docker-compose/initdb.sql
        target: /docker-entrypoint-initdb.d/initdb.sql
      - type: bind
        source: ./docker-compose/postgresql-custom.conf
        target: /opt/postgresql/conf.d/postgresql-custom.conf
      - type: volume
        source: pgdata_pub
        target: /var/lib/postgresql/data
volumes:
  pgdata_edit:
  pgdata_pub:
